/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's rot natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_ROT_LIST_H
#define BLUEWAKE_NATIVE_ROT_LIST_H

#define ROT_NATIVES(X) \
    X(0x80301150u, lfn_80301150, "JMAEulerToQuat", 80301150)

#endif
