/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's geom natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_GEOM_LIST_H
#define BLUEWAKE_NATIVE_GEOM_LIST_H

#define GEOM_NATIVES(X) \
    X(0x8024A6F0u, lfn_8024A6F0, "cM3d_CalcPla", 8024A6F0) \
    X(0x80254214u, lfn_80254214, "cSPolar::Val", 80254214) \
    X(0x8008A230u, lfn_8008A230, "dKyw_pntwind_get_info", 8008A230)

#endif
