/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's bgblk natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_BGBLK_LIST_H
#define BLUEWAKE_NATIVE_BGBLK_LIST_H

#define BGBLK_NATIVES(X) \
    X(0x80247C4Cu, lfn_80247C4C, "cBgW::MakeBlckMinMax", 80247C4C) \
    X(0x80247CD4u, lfn_80247CD4, "cBgW::MakeBlckBnd", 80247CD4)

#endif
