/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's calc natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_CALC_LIST_H
#define BLUEWAKE_NATIVE_CALC_LIST_H

#define CALC_NATIVES(X) \
    X(0x802460D0u, lfn_802460D0, "cM_atan2s", 802460D0)

#endif
