/* Generated by scripts/windows/native_gx_gen.py: the fifth set's natives by entry
 * (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_GX_LIST_H
#define BLUEWAKE_NATIVE_GX_LIST_H

#define GX_NATIVES(X) \
    X(0x80326F38u, gxn_80326F38, "GXLoadPosMtxImm", 80326F38) \
    X(0x80326F88u, gxn_80326F88, "GXLoadNrmMtxImm", 80326F88) \
    X(0x80325FA8u, gxn_80325FA8, "GXSetTevColor", 80325FA8) \
    X(0x8032601Cu, gxn_8032601C, "GXSetTevColorS10", 8032601C) \
    X(0x80326090u, gxn_80326090, "GXSetTevKColor", 80326090) \
    X(0x80322568u, gxn_80322568, "GXSetArray", 80322568) \
    X(0x803263A0u, gxn_803263A0, "GXSetTevOrder", 803263A0) \
    X(0x80326B80u, gxn_80326B80, "GXCallDisplayList", 80326B80) \
    X(0x803230C4u, gxn_803230C4, "GXBegin", 803230C4) \
    X(0x80324D50u, gxn_80324D50, "GXLoadTexObjPreLoaded", 80324D50) \
    X(0x80324EE8u, gxn_80324EE8, "GXLoadTexObj", 80324EE8) \
    X(0x803253B8u, gxn_803253B8, "__GXSetSUTexRegs", 803253B8) \
    X(0x803221D8u, gxn_803221D8, "__GXSetVAT", 803221D8) \
    X(0x80327364u, gxn_80327364, "__GXSetMatrixIndex", 80327364) \
    X(0x80325CD4u, gxn_80325CD4, "__GXUpdateBPMask", 80325CD4) \
    X(0x803233B0u, gxn_803233B0, "__GXSetGenMode", 803233B0) \
    X(0x80321958u, gxn_80321958, "__GXSetVCD", 80321958) \
    X(0x803214B0u, gxn_803214B0, "__GXXfVtxSpecs", 803214B0) \
    X(0x803219ACu, gxn_803219AC, "__GXCalculateVLim", 803219AC) \
    X(0x80322604u, gxn_80322604, "GXSetTexCoordGen2", 80322604) \
    X(0x803228D4u, gxn_803228D4, "GXSetNumTexGens", 803228D4) \
    X(0x80324390u, gxn_80324390, "GXSetChanAmbColor", 80324390) \
    X(0x80324484u, gxn_80324484, "GXSetChanMatColor", 80324484) \
    X(0x80324578u, gxn_80324578, "GXSetNumChans", 80324578) \
    X(0x803245BCu, gxn_803245BC, "GXSetChanCtrl", 803245BC) \
    X(0x80326FD8u, gxn_80326FD8, "GXSetCurrentMtx", 80326FD8) \
    X(0x803265A8u, gxn_803265A8, "GXSetFog", 803265A8) \
    X(0x80326758u, gxn_80326758, "GXSetFogRangeAdj", 80326758) \
    X(0x80324B68u, gxn_80324B68, "GXInitTexObjLOD", 80324B68) \
    X(0x80325810u, gxn_80325810, "GXSetIndTexMtx", 80325810) \
    X(0x802D85F8u, gxn_802D85F8, "J3DGDSetFog", 802D85F8) \
    X(0x802D80D0u, gxn_802D80D0, "J3DGDSetTevOrder", 802D80D0) \
    X(0x802AFDDCu, gxn_802AFDDC, "GFSetTevColor", 802AFDDC) \
    X(0x802AFE38u, gxn_802AFE38, "GFSetTevColorS10", 802AFE38) \
    X(0x802AFBD4u, gxn_802AFBD4, "GFSetFog", 802AFBD4)

#endif
