/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's libm natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_LIBM_LIST_H
#define BLUEWAKE_NATIVE_LIBM_LIST_H

#define LIBM_NATIVES(X) \
    X(0x8032EC1Cu, lfn_8032EC1C, "__ieee754_fmod", 8032EC1C) \
    X(0x80330E34u, lfn_80330E34, "fmod", 80330E34) \
    X(0x80246044u, lfn_80246044, "cM_rad2s", 80246044) \
    X(0x802462C8u, lfn_802462C8, "cM_rnd", 802462C8) \
    X(0x802463B0u, lfn_802463B0, "cM_rndF", 802463B0) \
    X(0x802463E8u, lfn_802463E8, "cM_rndFX", 802463E8) \
    X(0x80330C84u, lfn_80330C84, "sin", 80330C84) \
    X(0x8033071Cu, lfn_8033071C, "cos", 8033071C) \
    X(0x80330D5Cu, lfn_80330D5C, "tan", 80330D5C)

#endif
