/* Generated by scripts/windows/native_leaf_gen.py: the seventh set's jas natives by
 * entry (X(entry, native, name, the entry's digits)). Do not edit; regenerate. */
#ifndef BLUEWAKE_NATIVE_JAS_LIST_H
#define BLUEWAKE_NATIVE_JAS_LIST_H

#define JAS_NATIVES(X) \
    X(0x8028DF2Cu, lfn_8028DF2C, "JASystem::TOscillator::getOffset", 8028DF2C) \
    X(0x8028E238u, lfn_8028E238, "JASystem::TOscillator::calc", 8028E238) \
    X(0x8028C3A8u, lfn_8028C3A8, "JASystem::TChannel::updateEffectorParam", 8028C3A8)

#endif
